@startuml
left to right direction
skinparam packagestyle rectangle
actor Aluno
rectangle {
    Aluno -- (Adcionar documento)
    (Adcionar documento) ..> (Preencher informações sobre o documento): <<include>>
    (Adcionar documento) ..> (Carregar documento): <<include>>
    (Adcionar documento) ..> (Calcular pontos): <<includes>>
}
@enduml