@startuml
left to right direction
skinparam packagestyle rectangle
actor Aluno
rectangle "editar perfil de aluno" {
   Aluno -- (acessar perfil de conta)
    (acessar perfil de conta) ..> (fazer login): <<includes>>
    (acessar perfil de conta) ..> (editar dados da conta): <<extends>>
} 
@enduml