@startuml
left to right direction
skinparam packagestyle rectangle
actor aluno
rectangle "login de aluno" {
    aluno --> (Efetuar login de aluno)
    (Efetuar login de aluno) .> (autenticar aluno): <<include>>
    (Efetuar login de aluno) <.. (cadastrar aluno): <<extends>>
}
@enduml