@startuml
actor Professor
boundary "tela principal" as home
'boundary "tela de documentos" as documentos
control StudentController
'control DocumentController
entity StudentEntity
'entity DocumentEntity

Professor -> home: visualizar a lista de alunos
home ->> StudentController: requisitar lista de alunos
StudentController ->> StudentEntity: buscar por alunos
StudentEntity -->> StudentController: lista de alunos
StudentController -->> home: responder com a lista de alunos
home --> Professor: exibir lista de alunos

@enduml