@startuml
@startuml
actor Student
boundary "tela principal" as home
control DocumentController as control
entity DocumentEntity as entity

Student ->> home: selecionar documento
activate Student
activate home
Student ->> home: tentar atualizar documento
home ->> home: verificar se documento foi enviado para avaliação
alt documento não enviado para avaliação
  home ->> control: solicitar atualização do documento
  deactivate home
  activate control
  control -> entity: excluir documento
  deactivate control
  activate entity
  entity --> control: mensagem de confirmação
  deactivate entity
  activate control
  control -->> home: enviar mensagem de confirmação
  activate home
  deactivate control
  home -->> Student: exibir mensagem de confirmação 
  
  else document enviado para avaliação
    home -->> Student: atualização não permitida
end
@enduml
@enduml