@startuml
Actor Student
boundary "tela de cadastro de aluno" as cadastro
control StudentController
entity StudentEntity
Student ->> cadastro: entrar com dados necessarios
activate Student
activate cadastro
cadastro ->> cadastro: validar dados
cadastro ->> StudentController: enviar requisicao
activate StudentController
StudentController -> StudentEntity: salvar dados
deactivate StudentController
activate StudentEntity
StudentEntity --> StudentController: dados salvos
deactivate StudentEntity
activate StudentController
StudentController -->> cadastro: confirmação de cadastro
deactivate StudentController
cadastro -->> Student: estudante cadastrado
deactivate cadastro
@enduml