@startuml
actor Aluno
boundary "tela principal" as home
control DocumentController 
entity DocumentEntity

Aluno ->> home: ver documentos adicionados
home ->> DocumentController: requisitar os documentos adicionados
DocumentController ->> DocumentEntity: buscar pelos documentos adcionados
DocumentEntity -->> DocumentController: retornar com os documentos
DocumentController -->> home: responder com os documentos
home -->> Aluno: exibir lista de documentos
Aluno ->> home: ver documentos por grupo
home -->> Aluno: exibir documentos por grupo
@enduml