@startuml
left to right direction
skinparam packgestyle rectangle
actor Admin
rectangle "gerenciar grupos" {
  Admin -- (adicionar item)
  Admin -- (excluir item)
  Admin -- (editar item)
  (adicionar item) ..> (selecionar grupo): <<include>>
  (excluir item) ..> (selecionar grupo): <<include>>
  (editar item) ..> (selecionar grupo): <<include>>
}
@enduml