@startuml
left to right direction
skinparam packgestyle rectangle
actor Admin
rectangle "gerenciar professores" {
  Admin -- (selecionar curso)
  Admin -- (verificar se curso tem professor responsável)
  (verificar se curso tem professor responsável) <.. (adicionar professor responsável): <<extends>>
  (verificar se curso tem professor responsável) <.. (substituir professor responsável): <<extends>>
  Admin -- (informa dados de acesso ao professor)
}
@enduml