@startuml
actor Aluno
boundary "Tela de login" as login
control  StudentController
entity StudentEntity

Aluno ->> login: Solicitar acesso a conta
activate login
login ->> StudentController: Requisitar Autenticação
activate StudentController

StudentController -> StudentEntity: Buscar aluno
    activate StudentEntity
    alt Professor existe na base de dados
        
        StudentEntity --> StudentController: aluno encontrado
        'deactivate StudentController
         StudentController -> StudentController: Verificar dados do aluno
        alt dados válidos
            StudentController -->> login: Aluno Autenticado
            login -->> Aluno: Acesso permitido 
        else dados inválidos
            
            login <<-- StudentController: Não Autenticado
            login -->> Aluno: Acesso não permitido
        end
       
    else Aluno não cadastrado
        
        StudentEntity --> Aluno: aluno não encontrado
        deactivate StudentEntity
end

@enduml