@startuml
left to right direction
class Document {
    -name: string
    -ra: string
    -document: Document
}
class student
class professor
class group
class item
class documentController
class studentController
class professorController

interface Score {
    calcularPontosPorGrupo()
    calcularPontosTotal()
}
Document "1" --- "0..*" group
group o-- item: have >
documentController -- Document

student -- studentController
professor -- professorController
professor "1..*" -- "1" student
student "0..*" -- "1" Document


Score <.. documentController
@enduml